title: dlinsley.github.io
description: 
google_analytics: 
show_downloads: true

twitter_username: danlinsley
github_username:  dlinsley
clarity_header_iconshape: lightning
disqus_shortname: dlinsley-github-io

gems:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-avatar

compress_html:
  blanklines: true
