title: dlinsley.github.io
description: 
google_analytics: 
show_downloads: true

twitter_username: danlinsley
github_username:  dlinsley
clarity_header_iconshape: happy-face

gems:
  - jekyll-mentions

compress_html:
  blanklines: true